### PR TITLE
add  me.kittichdevs.com to webring

### PR DESCRIPTION
**Pull request by dadaKitt**

### CODE REVIEW

**Comment by dadaKitt** [comment]
Desktop = 
desktop

Mobile = 
mobile

**Comment by dtinth** [comment]
@dadaKitt hi! Many thanks for your interest in joining the webring!

Our webring requires that you publish some content on your own site, per the requirement here:

image

Can you add some contents to your site? Here are some ideas:

- Pages about the projects that you have worked on (portfolio)
- Articles about what you recently learned (blog)

Once you have some contents, I would be happy to add you to the webring!

**Comment by dadaKitt** [comment]
Update 👍
add blog and my project on me.kittichdevs.com
port1
port2
blog

**Comment by dtinth** [comment]
@dadaKitt Nice, that was quick!

Thanks, and welcome to the webring!

P.S. If you have a blog or a feed of your work, you can create an RSS feed, and put the URL in `data-feed` attribute. This way your latest entry will be shown on the feed (below the site list) and also get posted to [our Facebook page][fb]. Also you’re welcome to join [#webring on Bangkok Open Source Discord][discord].

[fb]: https://www.facebook.com/webring.in.th/
[discord]: https://discord.gg/vGZuKzqxQ4

**Pull request merged**
