### PR TITLE
Add `nitpum.com` to Webring

### PR DESCRIPTION
**Pull request by nitpum**
- Add nitpum.com to a list in `index.html`
- Webring icon at a footer of the page beside social icons

### CODE REVIEW

**Review by dtinth — COMMENTED** [review]
@nitpum Thanks! I saw that your site has an RSS feed at "https://nitpum.com/index.xml" but you did not include it here. Are you sure you don’t want to put your site’s latest article on the feed section?

**Comment by nitpum** [comment]
> @nitpum Thanks! I saw that your site has an RSS feed at "https://nitpum.com/index.xml" but you did not include it here in `data-feed`. Are you sure you don’t want to put your site’s latest article on the feed section?

Oh! I forgot that hugo already generated RSS feed for me. Thanks for mention.

**Review by dtinth — APPROVED** [review]
@nitpum  Thanks, and welcome to the webring!

**Comment by nitpum** [comment]
@dtinth Thank you! Did you forget to merge or something wrong?

**Comment by dtinth** [comment]
@nitpum Yes, I was on a BTS. Merging it in now, sorry for the wait.

**Pull request merged**
