### PR TITLE
add toupawa.com

### PR DESCRIPTION
**Pull request by Washira**
ตำแหน่งของไอคอนบน Desktop และ Mobile บน https://toupawa.com อยู่ด้านบนขวานะครับ

### CODE REVIEW

**Review by dtinth — CHANGES_REQUESTED** [review]
@Washira Thanks for your PR. Can you revert the changes not related to `index.html`?

- `.vscode/settings.json`
- `webring` (Git submodule)

Looking at https://github.com/wonderfulsoftware/webring/pull/56/files should show only 1 file changed krub

**Review by dtinth — COMMENTED** [review]
image

Please remove the submodule as well krubb (you may have cloned a nested `webring` repo inside `webring`)

**Review by dtinth — APPROVED** [review]
@Washira Thanks, and welcome to the webring!

**Comment by Washira** [comment]
Thank you for your attention.

**Pull request merged**
