### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Homiez09**

### CODE REVIEW

**Comment by dtinth** [comment]
@Homiez09 Hello and thanks for your interest in joining the webring.

Right now, it seems that your homepage only links to your social site, and the CV is empty. Can you add more content to your site? Maybe an about page or a blog post. This makes it satisfy the 2nd rule.

**Comment by Homiez09** [comment]
Sure. I'm currently in the process of updating it, and I plan to add a personal blog section. Additionally, I will work on creating an about page to provide more information about myself and my interests.

Thank You krub😺

**Comment by Homiez09** [comment]
@dtinth I already update my web.

**Comment by dtinth** [comment]
@Homiez09 
Thanks, and welcome to the webring!

**Pull request merged**
