### PR TITLE
feat: add new rss url for https://thiti.dev site

### PR DESCRIPTION
**Pull request by thiti-y**
Could you please marge this commit for add rss of my website.

Thank you.

### CODE REVIEW

**Comment by dtinth** [comment]
@thiti-y Sure, thanks!

**Comment by thiti-y** [comment]
@dtinth Thanks! 👍

**Comment by dtinth** [comment]
@thiti-y Please make sure that your post’s `pubDate` is accurate. Right now your latest post is dated `<pubDate>Fri, 28 Jan 2022 17:16:40 GMT</pubDate>` in the RSS but is actually posted on Dec 25 2021. Thank you krubbb 🙏

**Comment by thiti-y** [comment]
Sorry about that, I'm already fixed it.

Thank you.

**Pull request merged**
