### PR TITLE
Add janescience.com  🔬

### PR DESCRIPTION
**Pull request by Janescience**
This is my personal website . I attach link on the right navigation bar.

Screen Shot 2565-03-08 at 17 59 19

### CODE REVIEW

**Comment by Janescience** [comment]
Icon on mobile.
Screen Shot 2565-03-09 at 14 32 01

**Comment by dtinth** [comment]
The bot’s suggestion to `##janescience.com` is incorrect, should be just `#janescience.com`

**Comment by Janescience** [comment]
Ok , I fixed.

**Review by dtinth — APPROVED** [review]
@Janescience Thanks, and welcome to the webring!

I saw that you have an RSS feed at https://janescience.com/rss.xml, however the `<link>` tags are pointing to the wrong domain (`https://gatsbystarterblogsource.gatsbyjs.io` instead of `https://janescience.com`).

Once you fix that, please feel free to add your RSS feed URL to the `data-feed` attribute, so that the webring’s homepage will list your latest article on the feed. Cheers!

**Pull request merged**
