### PR TITLE
add wiennat.com

### PR DESCRIPTION
**Pull request by wiennat**

### CODE REVIEW

**Review by dtinth — COMMENTED** [review]
Will review once I'm inside. (Sent from mobile.)

I like the Previous/List/Next link which links directly. However new links can be added and broken ones removed. Can you link to the ring like this?

```
#wiennat.com:next
#wiennat.com:prev
#wiennat.com:list
#wiennat.com:random
```

Then I will implement the logic to direct the user accordingly. This also lets me track webring usage stats.

Thanks!

**Comment by wiennat** [comment]
may I also have prev5 and next5 as we usually see them in conventional webrings?

**Comment by dtinth** [comment]
@wiennat Thanks for your suggestion! I have never used previous 5 and next 5, in fact I never used old-school webring, can you describe what it looks like, or do you have an example?

When user enters a webring, they have a chance to navigate before joining. So, unlike a conventional webring, where user is forwarded to the next site immediately, they arrive at portal first.

Anyways, I will merge for now, thanks, and welcome to the webring!

Note; These functionalities will be implemented later because I will refactor the code first.

**Comment by wiennat** [comment]
@dtinth An old school webring is not different much to what we have here. Except that, it is common to see links to neighbor websites in the webring like I have placed mine. When the webring getting bigger, they had `next 5` / `prev 5` links. That's all I can remember.

**Comment by dtinth** [comment]
@wiennat FTR, the next 5 / prev 5 pages look like this, [thanks Archive.org](https://web.archive.org/web/20151029091114/http://nav.webring.org/cgi-bin/navcgi?ring=trust_web;id=8;next5). Seems like they too do screenshots of the website.

webring

Since the webring doesn’t take user to the next website upon `#<domain>:next`, I think next 5 is unnecessary. Actually, for the initial implementation, `#<domain>:next` will be equivalent to `#<domain>` (since that one presses [Next] automatically). You can add `:next5` and `:prev5`, but for now (once the initial implementation is there) the webring will treat them as `:next` and `:prev`. How does that sound?

**Comment by wiennat** [comment]
Sounds good to me. Many thanks.

**Pull request merged**
