### PR TITLE
add khet.tech to webring

### PR DESCRIPTION
**Pull request by khetkoong**
Desktop and Mobile views kub
Screen Shot 2566-04-04 at 23 39 46

Screen Shot 2566-04-04 at 23 40 11

### CODE REVIEW

**Comment by dtinth** [comment]
@khetkoong Hi! Many thanks for your interest in joining the webring!

Our webring requires that you publish some content on your own site, per the requirement here:

image

Can you add some contents to your site? Here are some ideas:

- Pages about the projects that you have worked on (portfolio)
- Articles about what you recently learned (blog)

**Comment by khetkoong** [comment]
🫡🫡🫡🫡

**Comment by khetkoong** [comment]
@dtinth I already add my blog to my website please check again [khet.tech/blogs](https://www.khet.tech/blogs)
Please let me know if you want something more.

**Comment by dtinth** [comment]
@khetkoong This looks good now. Thanks, and welcome to the webring!

By the way now that you have a blog, I recommend adding an RSS feed and put the URL in `data-feed` attribute. This way your latest post will be shown on the feed (below the site list) and also get posted to [our Facebook page][fb]. You can do that in a separate pull request, I am merging in this one now. Cheers!

[fb]: https://www.facebook.com/webring.in.th/

**Pull request merged**
