### PR TITLE
Add heyfirst.co to Webring

### PR DESCRIPTION
**Pull request by heyfirst**
Hi! I have attached webring icon to my website.

### CODE REVIEW

**Review by dtinth — APPROVED** [review]
@heyfirst Thanks, and welcome to the webring!

**Comment by dtinth** [comment]
@heyfirst Hi, I noticed that the backlink did not point to your domain, but is a placeholder. Please fix this for correct ring linking krub 😄 

```diff
-<a href="https://webring.wonderful.software#YOUR.DOMAIN" title="วงแหวนเว็บ">
-<a href="https://webring.wonderful.software#heyfirst.co" title="วงแหวนเว็บ">
```

Thanks!

**Comment by heyfirst** [comment]
@dtinth Oh noooooo. that's my fault. I fixed it. Thanks for let me know kubbb

**Comment by dtinth** [comment]
@heyfirst Thanks for fixing krub! It is always good that cases like this happen — because they indicate that _the system can be improved_. The semi-automatic PR reviewing system now handles this case: https://github.com/wonderfulsoftware/webring/commit/8361f3d256d8ed87e1b272d124bde7eb0897db9d. As you can see, you’re not the first one with incorrect backlink 😉. Cheers!

**Pull request merged**
